name: "Trustify SBOM Upload"
description: "Upload an SBOM to a Trustify instance"
inputs:
  target:
    description: The target API to send to
    required: true
  files:
    description: The SBOM files to upload
    required: true
  issuerUrl:
    description: An OIDC issuer URL for acquiring a bearer token
    required: false
  clientId:
    description: An OIDC client ID
    required: false
  clientSecret:
    description: A secret for the OIDC client
    required: false

runs:
  using: "composite"
  steps:
    - name: Download
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -sSL https://github.com/ctron/csaf-walker/releases/download/v0.8.9/sbom-x86_64-unknown-linux-gnu -o ${RUNNER_TOOL_CACHE}/sbom

    - name: Download
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -sSL https://github.com/ctron/csaf-walker/releases/download/v0.8.9/sbom-x86_64-apple-darwin -o ${RUNNER_TOOL_CACHE}/sbom

    - name: Download
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl -sSL https://github.com/ctron/csaf-walker/releases/download/v0.8.9/sbom-x86_64-pc-windows-msvc.exe  -o ${RUNNER_TOOL_CACHE}/sbom.exe

    - name: Run
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
        FILES: ${{ inputs.files }}
        OIDC_ISSUER_URL: ${{ inputs.issuerUrl }}
        OIDC_CLIENT_ID: ${{ inputs.clientId }}
        OIDC_CLIENT_SECRET: ${{ inputs.clientSecret }}
      run: |
        "${{ github.action_path }}/action.sh" "$TARGET" "$FILES" 
